[package]
name = "generator-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cube-lib = { path = "../cube-lib" }
rand = "0.8.5"
