[package]
name = "fmc-trainers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cube-lib = { git = "https://github.com/b-paul/cube-lib", rev = "edee44b" }
